// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'E:/Code/Projects/easy-api-master/easyapi-frontend/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import UserOutlined from 'E:/Code/Projects/easy-api-master/easyapi-frontend/node_modules/@ant-design/icons/es/icons/UserOutlined';
import CrownOutlined from 'E:/Code/Projects/easy-api-master/easyapi-frontend/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from 'E:/Code/Projects/easy-api-master/easyapi-frontend/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, UserOutlined, CrownOutlined, TableOutlined };
